name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, edited]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:        
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Front-End
    steps:
    - name: Assign issues with `frontend` label to Front-End Project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'frontend') ||
        contains(github.event.pull_request.labels.*.name, 'frontend')
      with:
        project: 'https://github.com/ShrillShrestha/digital-diary/projects/1'
        column_name: "To Do üìí"
    - name: Notify Front End issue on discord server
      if: |
        contains(github.event.issue.labels.*.name, 'frontend') ||
        contains(github.event.pull_request.labels.*.name, 'frontend')
      run: |
       curl -s -X POST "${{ secrets.DISCORD_FRONT_END_ISSUE }}" -d "content=Hey! There is a new Front-End Issue: ${{github.event.issue.title}} üé®! Check it at the FE Project! https://github.com/ShrillShrestha/digital-diary/projects/1"
         

    - name: Assign issues with `backend` label to Back-End Project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'backend') ||
        contains(github.event.pull_request.labels.*.name, 'backend')
      with:
        project: 'https://github.com/ShrillShrestha/digital-diary/projects/2'
        column_name: "To Do üìí"
    - name: Notify Back End issue on discord server
      if: |
        contains(github.event.issue.labels.*.name, 'backend') ||
        contains(github.event.pull_request.labels.*.name, 'backend')
      run: |
       curl -s -X POST "${{ secrets.DISCORD_BACK_END_ISSUE }}" -d "content= Looks like we need to do some BE changes: ${{github.event.issue.title}} üíªüíæ! Check it at the BE Project! https://github.com/ShrillShrestha/digital-diary/projects/2"
        
    - name: Assign issues with `documentation` label to Project Planning Project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'documentation') ||
        contains(github.event.pull_request.labels.*.name, 'documentation')
      with:
        project: 'https://github.com/ShrillShrestha/digital-diary/projects/3'
        column_name: "To Do üìí"
    - name: Notify Documentation issue on discord server
      if: |
        contains(github.event.issue.labels.*.name, 'documentation') ||
        contains(github.event.pull_request.labels.*.name, 'documentation')
      run: |
       curl -s -X POST "${{ secrets.DISCORD_PROJECT_PLANNING_ISSUE }}" -d "content= Wow! Looks like there are some changes into the documentation of the project: ${{github.event.issue.title}}üìù! Check it at the Project Planning Project! https://github.com/ShrillShrestha/digital-diary/projects/3"
     
    - name: Assign issues with `wishlist` label to Project Planning Project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'wishlist') ||
        contains(github.event.pull_request.labels.*.name, 'wishlist')
      with:
        project: 'https://github.com/ShrillShrestha/digital-diary/projects/4'
        column_name: "Wishlist üéÖ"
    - name: Notify that someone has a new wish on discord server
      if: |
        contains(github.event.issue.labels.*.name, 'wishlist') ||
        contains(github.event.pull_request.labels.*.name, 'wishlist')
      run: |
       curl -s -X POST "${{ secrets.DISCORD_WISHLIST_ISSUE }}" -d "content=Could \" ${{github.event.issue.title}} \" be a wish that will come true ‚ú® ? Check it at the wishlist Project! https://github.com/ShrillShrestha/digital-diary/projects/4"
  
